# Generated by Django 2.2.7 on 2020-01-05 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IMG_B', models.CharField(max_length=200, null=True)),
                ('IMG_A', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
