# Generated by Django 2.2.7 on 2020-01-27 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_upload', '0002_auto_20200107_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.TextField(null=True),
        ),
    ]
