# Generated by Django 2.2.7 on 2020-01-28 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_upload', '0004_auto_20200128_0017'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='label',
            field=models.IntegerField(null=True),
        ),
    ]
