# Generated by Django 2.2.7 on 2020-01-28 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_upload', '0005_photo_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='label',
            field=models.IntegerField(default=1),
        ),
    ]
