# Generated by Django 2.2.7 on 2020-02-06 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_upload', '0006_auto_20200128_2243'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='converted',
            field=models.BooleanField(default=False),
        ),
    ]
